const fs=require('fs'),path=require('path');
const root='C:\\Users\\lenovo\\pokedax\\pokedax\\pokedax';
const files=[
  ["src/app/api/bootstrap/jp-cards/route.ts","\"use server\";\nimport { createClient } from \"@supabase/supabase-js\";\nimport { NextResponse } from \"next/server\";\n\nconst TCGDEX_BASE = \"https://api.tcgdex.net/v2\";\nconst JP_SETS = [\"sv1s\",\"sv2a\",\"sv3a\",\"sv4a\",\"sv4k\",\"sv5a\",\"sv5k\",\"sv6\",\"sv6a\",\"sv7\",\"sv8\",\"sv8a\",\n  \"s1a\",\"s1h\",\"s2a\",\"s3a\",\"s4\",\"s4a\",\"s5a\",\"s6a\",\"s7d\",\"s7r\",\"s8\",\"s8a\",\"s9\",\"s9a\",\"s10\",\"s10a\",\"s10b\",\"s11\",\"s11a\",\"s12\"];\n\nexport async function GET(request: Request) {\n  const { searchParams } = new URL(request.url);\n  if (searchParams.get(\"secret\") !== process.env.ADMIN_SECRET) {\n    return NextResponse.json({ error: \"Unauthorized\" }, { status: 401 });\n  }\n\n  const limit = parseInt(searchParams.get(\"limit\") ?? \"5\");\n  const supabase = createClient(\n    process.env.NEXT_PUBLIC_SUPABASE_URL!,\n    process.env.SUPABASE_SERVICE_ROLE_KEY!\n  );\n\n  let totalCards = 0, totalSets = 0;\n  const setsToProcess = JP_SETS.slice(0, limit);\n\n  for (const setId of setsToProcess) {\n    try {\n      // Fetch set info\n      const setRes = await fetch(`${TCGDEX_BASE}/en/sets/${setId}`, {\n        headers: { \"User-Agent\": \"pokedax/1.0\" }\n      });\n      if (!setRes.ok) continue;\n      const setData = await setRes.json();\n\n      // Upsert set\n      await supabase.from(\"sets\").upsert({\n        id:           setId,\n        name:         setData.name,\n        name_de:      setData.name,\n        series:       setData.serie?.name ?? \"Japanese\",\n        card_count:   setData.cardCount ?? setData.cards?.length ?? 0,\n        release_date: setData.releaseDate ?? null,\n        logo_url:     setData.logo ?? null,\n        image_url:    setData.logo ?? null,\n        language:     \"ja\",\n      }, { onConflict: \"id\" });\n\n      totalSets++;\n\n      // Fetch cards\n      if (!setData.cards?.length) continue;\n      const cards = setData.cards.slice(0, 200);\n\n      for (let i = 0; i < cards.length; i += 50) {\n        const chunk = cards.slice(i, i + 50);\n        const rows = chunk.map((c: any) => ({\n          id:        `${setId}-${c.localId}`,\n          set_id:    setId,\n          name:      c.name,\n          name_de:   c.name,\n          number:    String(c.localId),\n          image_url: c.image ? `${c.image}/high.webp` : null,\n          language:  \"ja\",\n          category:  c.category ?? \"Pokemon\",\n        }));\n        await supabase.from(\"cards\").upsert(rows, { onConflict: \"id\" });\n        totalCards += rows.length;\n      }\n    } catch (err) {\n      console.error(`Error processing ${setId}:`, err);\n    }\n  }\n\n  return NextResponse.json({ totalSets, totalCards, setsProcessed: setsToProcess });\n}\n"],
];
for(const [rel,c] of files){
  const f=path.join(root,rel);
  fs.mkdirSync(path.dirname(f),{recursive:true});
  fs.writeFileSync(f,c,'utf8');
  console.log('OK '+rel);
}
console.log('Done chunk 3');